# Generated by Django 5.1.3 on 2025-10-24 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effecting_app', models.CharField(max_length=100)),
                ('cr_number', models.CharField(blank=True, max_length=200, unique=True)),
                ('cr_raised_by', models.CharField(max_length=100)),
                ('cr_raised_on', models.DateField(default=django.utils.timezone.now)),
                ('cr_approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('cr_approved_on', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('details_pre_cr', models.TextField(blank=True, null=True)),
                ('details_post_cr', models.TextField(blank=True, null=True)),
                ('back_up', models.CharField(max_length=100)),
                ('process_manager', models.CharField(max_length=100)),
                ('resource_name', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('identified_risks', models.TextField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('tested_on', models.DateField(blank=True, null=True)),
                ('validated_on', models.DateField(blank=True, null=True)),
                ('result_state', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('change_benefits', models.TextField(blank=True, null=True)),
                ('impacting_customer', models.CharField(max_length=100)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('implemented', 'Implemented')], default='draft', max_length=20)),
            ],
        ),
    ]
