# Generated by Django 5.1.3 on 2025-10-28 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contec_cr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='cr_approved_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='Approved By User'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='cr_number',
            field=models.CharField(blank=True, editable=False, max_length=200, unique=True),
        ),
    ]
