# Generated by Django 5.2.7 on 2026-01-14 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='partprice',
            index=models.Index(fields=['startdate', 'enddate'], name='price_book__startda_b8452a_idx'),
        ),
    ]
