# Generated by Django 5.2.6 on 2025-10-05 08:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210322_2234'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(choices=[('Mediacom', 'Mediacom'), ('Midco', 'Midco'), ('Frontier', 'Frontier')], max_length=50, verbose_name='Customer')),
                ('inv_type', models.CharField(choices=[('Fulfillment', 'Fulfillment'), ('C&C', 'C&C'), ('OME', 'OME')], max_length=50, verbose_name='Invoice Type')),
                ('issue_cat', models.CharField(choices=[('ManError', 'Man Error'), ('MachineError', 'Machine Error'), ('MaterialError', 'Material Error'), ('MethodError', 'Method Error'), ('MeasureableError', 'Measurable Error')], max_length=50, verbose_name='Issue Category')),
                ('description', models.TextField(default='No content provided.', verbose_name='Description')),
                ('identified_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Identified On')),
                ('identified_by', models.CharField(max_length=75, verbose_name='Identified By')),
                ('revenue_impact', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Revenue Impact ($)')),
                ('impact_category', models.CharField(blank=True, choices=[('Undercharge', 'Undercharge'), ('Overcharge', 'Overcharge'), ('Credit', 'Credit'), ('Debit', 'Debit')], max_length=50, null=True, verbose_name='Impact Category')),
                ('root_cause', models.CharField(max_length=200, verbose_name='Root Cause')),
                ('root_cause_owner', models.CharField(max_length=75, verbose_name='Root Cause Owner')),
                ('customer_received', models.BooleanField(default=False, verbose_name='Customer Received')),
                ('impacted_customer', models.CharField(blank=True, choices=[('Mediacom', 'Mediacom'), ('Midco', 'Midco'), ('Frontier', 'Frontier')], max_length=50, null=True, verbose_name='Impacted Customer')),
                ('containment_action', models.TextField(default='No content provided.', verbose_name='Containment Action')),
                ('corrective_action', models.TextField(default='No content provided.', verbose_name='Corrective Action')),
                ('rebilled_credited', models.BooleanField(default=False, verbose_name='Rebilled/Credited')),
                ('action_owner', models.CharField(blank=True, default='No Action Owner', max_length=75, null=True, verbose_name='Action Owner')),
                ('due_date', models.DateTimeField(verbose_name='Due Date')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Dismissed', 'Dismissed')], default='Open', max_length=50, verbose_name='Status')),
                ('approved', models.CharField(blank=True, choices=[('patrick', 'Patrick'), ('neha', 'Neha')], max_length=50, null=True, verbose_name='Approved By')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_view_issue', 'Can view issue'), ('can_add_issue', 'Can add issue'), ('can_change_issue', 'Can change issue'), ('can_delete_issue', 'Can delete issue'), ('can_export_issue', 'Can export issue'), ('can_import_issue', 'Can import issue')],
            },
        ),
    ]
