# Generated by Django 4.2.7 on 2025-10-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_finalize_fk_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload documents (.pdf, .docx, .xlsx) or images (.jpg, .png, .gif)', null=True, upload_to='issue_attachments/%Y/%m/', verbose_name='Attachment'),
        ),
    ]
