# Generated by Django 5.2.7 on 2025-10-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_add_missing_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='action_owner',
            field=models.CharField(blank=True, default=' ', max_length=75, null=True, verbose_name='Action Owner'),
        ),
    ]
