# Generated by Django 5.2.7 on 2025-10-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_tips',
            field=models.BooleanField(default=True, verbose_name='Show Tips on Issue Create'),
        ),
    ]
