# Generated by Django 5.1.3 on 2025-10-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_boolean_to_yesno'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='location',
            field=models.CharField(blank=True, help_text='Physical or logical location related to the issue (e.g., Site A, Router-12, Billing Zone)', max_length=200, null=True, verbose_name='Location'),
        ),
    ]
