# Generated by Django 5.2.7 on 2025-10-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_issue_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-id'], 'permissions': [('can_view_issue', 'Can view issue'), ('can_add_issue', 'Can add issue'), ('can_change_issue', 'Can change issue'), ('can_delete_issue', 'Can delete issue'), ('can_export_issue', 'Can export issue'), ('can_import_issue', 'Can import issue')]},
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
