# Generated by Django 5.1.3 on 2025-10-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_issue_options_alter_issue_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_access_approvals',
            field=models.BooleanField(default=False, verbose_name='Can Access CR Approvals'),
        ),
    ]
