# Generated by Django 5.2.7 on 2026-02-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='approved',
            field=models.CharField(blank=True, choices=[('patrick', 'Patrick'), ('neha', 'Neha'), ('verle', 'Verle'), ('prabhu', 'Prabhu')], max_length=50, null=True, verbose_name='Approved By'),
        ),
    ]
